✨ Feature/add rabbitmq dag
fearless-pioneer/simple-dataops-docker pull request #12
Opened 2023-06-11 04:03 UTC by Kimdongui

## Changes?

- RabbitMQ의 Queue로 현재 시간(KST)를 publish 하는 DAG 작성

## Test?

- `make all` 후 [`airflow-webserver`](localhost:8008) 에서 dag 동작

2023-06-11 06:39 UTC, dongminlee94 requested changes

2023-06-11 06:39 UTC, dongminlee94 commented on docker/airflow/Dockerfile
> +    pip install psycopg2-binary apache-airflow[celery,redis]==2.5.0 pika
pika의 버전을 정확히 명시하면 좋을 것 같아요~

2023-06-11 06:39 UTC, dongminlee94 commented on pyproject.toml
> +urllib3 = "1.26.16"
이거는 왜 필요한가요?

2023-06-11 06:39 UTC, dongminlee94 commented on src/dags/rabbitmq-producer.py
> +    import datetime
import는 맨 위로 빼도 될 것 같아요~

2023-06-12 11:47 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
`urllib3`가 왜 필요한지 여쭤보시는 걸까요?

2023-06-12 11:49 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
![image](https://github.com/fearless-pioneer/simple-dataops-docker/assets/65523228/ec27f753-9c94-4d49-8a13-e8a6970d628d)

다음과 같은 에러가 poetry에서 발생합니다. `pika` 보다는 poetry의 문제였던걸로 기억합니다!

2023-06-12 11:50 UTC, Kimdongui commented on src/dags/rabbitmq-producer.py
> +    import datetime
해당 task 에서 사용하는 것이라 우선 저렇게 작성했습니다! 위로 빼도 상관은 없을 것 같아 위로 빼두겠습니다~!

2023-06-12 11:52 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
**Full error loop**
![image](https://github.com/fearless-pioneer/simple-dataops-docker/assets/65523228/3c1a65eb-3063-4059-9e06-286fa86a0287)


- [Related issue](https://github.com/python-poetry/poetry/issues/7936)
- [Solution](https://github.com/python-poetry/poetry/issues/7936#issuecomment-1556169616)

2023-06-12 11:58 UTC, Kimdongui commented on src/dags/rabbitmq-producer.py
> +    import datetime
Done :)

2023-06-12 12:00 UTC, Kimdongui commented on docker/airflow/Dockerfile
> +    pip install psycopg2-binary apache-airflow[celery,redis]==2.5.0 pika
Done :)

2023-06-12 12:03 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
poetry에서 사용하는 `urllib3` 의 버전이 1.~ 버전인데, `urllib3`가 자체적으로 2.~ 버전으로 올리면서 interface 등 몇 가지 기능 동작이 바뀌면서 발생한 일인 것 같습니다. poetry 버전이 올라가면서 해결 될 것 같으나 당장은 `urllib3==1.26.XX` 버전을 설치해서 사용해야 할 것 같습니다 😭

2023-06-12 13:03 UTC, dongminlee94 commented on pyproject.toml
> +urllib3 = "1.26.16"
오 그렇군요 그러면 다시 추가해야하는거죠?

2023-06-12 13:21 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
네네 추가해서 반영해두겠습니다~!

2023-06-12 13:23 UTC, Kimdongui commented on pyproject.toml
> +urllib3 = "1.26.16"
Done.

2023-06-24 10:38 UTC, dongminlee94 requested changes

2023-06-24 10:38 UTC, dongminlee94 commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    queue_name: str = "rabbitmq-demo-queue",
```suggestion
    queue_name: str = "rabbitmq-simple-queue",
```
demo -> simple 어떠세요?

References:
- AWS SQS (**Simple** Queue Service)
- **Simple** DataOps Docker

2023-06-24 10:38 UTC, dongminlee94 commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    start_date = str(datetime.strptime(str(task_time), "%Y-%m-%d %H:%M:%S") + timedelta(hours=9))
data generator에서 timezone을 seoul로 해서 마지막에 `timedelta(hours=9)` 하지 않아도 될 것 같은데, 시간 체크 한번 하면 좋을 것 같아요. 괜히 한국시간인데.. 9시간 더했다간... 어디 시간이죠 그러면..?ㅋㅋㅋ

https://github.com/fearless-pioneer/simple-dataops-docker/blob/main/docker/data-generator/data_generator.py#L38

2023-06-24 10:38 UTC, dongminlee94 commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    queue = channel.queue_declare(queue=queue_name)
간단히 annotation 달아두면 어떨까요? 뭘하는건지 짧게 적어두면 좋을 것 같아요~

2023-06-24 10:39 UTC, dongminlee94 commented
@Kimdongui 동현님 readme 적어주셔야 해요~~

2023-06-24 10:41 UTC, dongminlee94 commented
@Kimdongui 동현님 PR에서 아래에 task_id 변경 좀 해주실 수 있으실까요?
https://github.com/fearless-pioneer/simple-dataops-docker/blob/main/src/dags/2_batch_glue/dag.py#L28

"task_1" -> "run-batch-glue"

2023-06-25 02:18 UTC, Kimdongui commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    start_date = str(datetime.strptime(str(task_time), "%Y-%m-%d %H:%M:%S") + timedelta(hours=9))
`task_time` 기준이면 `Airflow` 의 `ts` context variable 인데 더해주는 것이 맞지 않을까요??! 한번 확인해보겠습니다!

2023-06-25 04:34 UTC, Kimdongui commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    start_date = str(datetime.strptime(str(task_time), "%Y-%m-%d %H:%M:%S") + timedelta(hours=9))
확인해보니 `ts` 가 UTC 이기 때문에 더해주는 것이 KST 에 맞습니다!

2023-06-25 04:35 UTC, Kimdongui commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    queue = channel.queue_declare(queue=queue_name)
달아두었습니다~!

2023-06-25 04:36 UTC, Kimdongui commented
> @Kimdongui 동현님 PR에서 아래에 task_id 변경 좀 해주실 수 있으실까요? https://github.com/fearless-pioneer/simple-dataops-docker/blob/main/src/dags/2_batch_glue/dag.py#L28
> 
> "task_1" -> "run-batch-glue"

추가하였습니다!

2023-06-25 05:37 UTC, Kimdongui commented
@dongminlee94 README 작성도 마무리했습니다!

2023-06-25 05:38 UTC, Kimdongui commented on src/dags/3_batch_sqs/rabbitmq_producer.py
> +    queue_name: str = "rabbitmq-demo-queue",
변경했습니다 😎

2023-06-25 07:34 UTC, dongminlee94 approved these changes
LGTM~!

2023-06-25 07:48 UTC, merged